### ISSUE TITLE
Where is the MongoDB integration?

### ISSUE THREAD

**Issue by sebkouba** [wlepinski/generator-meanstack#14]
Thanks for providing the generator. Unfortunately I'm either missing something or it's not quite providing what I'm looking for. Is there any provision for integrating a mongdodb instance in the generator? 

I'm still learning and need some crutches getting express and mongodb going which I was hoping this generator would do. How would I proceed to actually integrate the "M" of the mean stack?

Thanks again!

**Comment by wlepinski** [comment]
@SebKouba I'm planning the scaffold generation for the next major release. I had a busy 2013 and don't had much time to work on this project. The fact is that I'm planning to provide only the basic generator, something like Rails and other MVC framework does.

For now you can read some tutorials, there's ton of them around the web:
To help you out I have compiled some sources so that you can get started:
- http://cwbuecheler.com/web/tutorials/2013/node-express-mongo/
- http://howtonode.org/express-mongodb
- http://dreamerslab.com/blog/en/write-a-todo-list-with-express-and-mongodb/

**Comment by wlepinski** [comment]
Just to keep track of what we need to do. 
https://github.com/wlepinski/generator-meanstack/issues?milestone=1

**Comment by sebkouba** [comment]
Thanks for the prompt reply and the helpful links! 

I've looked at the other popular MEAN generator and it just comes with a lot of stuff, I guess more than I can/want to handle right off the bat. I'll play around with your generator and see if I can make some suggestions and come up with potential solutions. I like the idea of integrating mongolab, because it avoids complications for the initial setup and allows for rapid prototyping which I assume people are after when they use generators.

**Comment by wlepinski** [comment]
@SebKouba Would be great have suggestions during this step. I created yesterday a milestone with some macro tasks that need to be done to complete the MEAN stack. If you want to get in touch of what I'm doing you can look into the wip-1.0.0 branch and the milestone completeness.
