### ISSUE TITLE
How do I deploy this?

### ISSUE THREAD

**Issue by johnjelinek** [wlepinski/generator-meanstack#2]
(Let me know if there is a better place to leave questions, like StackOverflow)

If I want a server to host both the front and back ends of the app from meanstack, what is the recommend way to deploy? I imagine it would work like this:
1. `grunt build:dist`
2. Point apache/nginx to `dist` directory
3. `node server.js` to start up api that the front-end will interact with
4. Have nginx reverse proxy this so it will point to someurl.com/api/someresource

Is this what you had in mind?

**Comment by wlepinski** [comment]
If you set an env variable NODE_ENV=production express knows how to get static files from the dist folder. So you don't need to reverse.

I used Heroku quite a lot and the deploy is very easy. Just push the project to some project there and you are good to go.

**Comment by jamespakele** [comment]
Regarding deployment to Heroku... Do you deploy the whole project or just the "dist" folder? And if only the "dist" folder what is the Procfile entry? 

Sorry, I'm a noob trying to find my way around this...

**Comment by wlepinski** [comment]
@jamespakele You need to push everything to Heroku.

**Comment by johnjelinek** [comment]
What is the recommended approach when not using heroku?

**Comment by wlepinski** [comment]
@johnjelinek Generate the build using <code>grunt build</code>. Then you can FTP or SCP everything to your server. Make sure that you have the **NODE_ENV=production** on the server.

On this model you can also exclude the app folder because Express will take care of getting static resources only from the dist folder.

If you have doubts about how Express redirect from app -> dist folder take a look at the files inside https://github.com/wlepinski/generator-meanstack/tree/master/app/templates/config/environments
